
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author zanina
 */
public class Imenik extends javax.swing.JPanel {
// public static void main(String[] arguments) {
//     Imenik prikazi = new Imenik();
//     
//     prikazi.prikaziActionPerformed(null);
//     
// }
    /**
     * Creates new form Imenik
     */
    public Imenik() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        priimek = new javax.swing.JTextField();
        kraj = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        stevilka = new javax.swing.JTextField();
        dodaj = new javax.swing.JButton();
        prikazi = new javax.swing.JButton();

        jLabel1.setText("Priimek");

        kraj.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel2.setText("Kraj");

        jLabel3.setText("Telefonska stevilka");

        dodaj.setText("Dodaj");
        dodaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dodajActionPerformed(evt);
            }
        });

        prikazi.setText("Prikazi vse");
        prikazi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prikaziActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(prikazi)
                        .addGap(18, 18, 18)
                        .addComponent(dodaj))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(kraj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(priimek, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                            .addComponent(stevilka))))
                .addContainerGap(187, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(priimek, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kraj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(stevilka, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dodaj)
                    .addComponent(prikazi))
                .addContainerGap(134, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void prikaziActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prikaziActionPerformed
        // TODO add your handling code here:
         
        String data = "jdbc:derby://localhost:1527/Oseba";
        try (
                Connection conn = DriverManager.getConnection(
                        data);
                Statement st = conn.createStatement()) {

                    Class.forName("org.apache.derby.jdbc.ClientDriver");

                    ResultSet rec = st.executeQuery(
                            "select IdOseba, Priimek, posta, Stevilka "
                            + "from APP.Oseba "
                            + "order by IdOseba");
                    while (rec.next()) {
                        System.out.println("IdOseba:\t"
                                + rec.getString(1));
                        System.out.println("Priimek:\t" + rec.getString(2));
                        System.out.println("Kraj:\t" + rec.getInt(3));
                        System.out.println("Stevilka:\t" + rec.getString(4));
                        System.out.println();
                    }
                    st.close();
                } catch (SQLException s) {
                    System.out.println("SQL Error: " + s.toString() + " "
                            + s.getErrorCode() + " " + s.getSQLState());
                } catch (Exception e) {
                    System.out.println("Error: " + e.toString()
                            + e.getMessage());
                }
         
    }//GEN-LAST:event_prikaziActionPerformed

    private void dodajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dodajActionPerformed
        // TODO add your handling code here:
        
    
    }//GEN-LAST:event_dodajActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton dodaj;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JComboBox kraj;
    private javax.swing.JTextField priimek;
    private javax.swing.JButton prikazi;
    private javax.swing.JTextField stevilka;
    // End of variables declaration//GEN-END:variables
}
